# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              DevXOps
description:        Documentation for DevXOps a developer community.
lang:               en

# Site subpath, e.g. /blog
domain: htxsg.github.io      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://htxsg.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /htxsg.github.io/docs/      # place folder name if the site is served in a subfolder

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Ng Pan Yong
    title:          The Cloud Guy 
    avatar:         avatar-py.jpg

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    panyong:
      name:         Ng Pan Yong
      title:        The Cloud Guy   
      avatar:       avatar-py.jpg
    kevin:
      name:         Kevin Chan
      title:        Cloud Archtect
      avatar:       avatar-evan.png
    lina:
      name:         Ding Li Na
      title:        Cloud Evangelist     
      avatar:       avatar-sara.png
    yongwee:
      name:         Goh Yong Wee
      title:        DevOps Engineer     
      avatar:       avatar-alex.png
    ivan:
      name:         Lester Lim
      title:        CLoud Engineer      
      avatar:       avatar-daniel.png
    raj:
      name:         Raj Senthil
      title:        Lead DevOps Engineer     
      avatar:       avatar-tom.png

# Social icons displayed in footer
social:
    email:
    website:        https://www.htx.gov.sg
    facebook:       https://www.facebook.com/HTXSG
    flickr:
    dribbble:
    github:         https://github.com/htxsg
    googleplus:
    instagram:      https://www.instagram.com/htxsg/
    linkedin:
    pinterest:
    twitter:        
    vimeo:          
    youtube:        https://www.youtube.com/channel/UCP861oMccv87ej7rcGJtHTw

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            false # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       false # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      2022 <a href="https://www.htx.gov.sg/">Home Team Science and Technology Agency</a>  

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  skills:
    output:         true
  pages:
    output:         false


# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
  # _skills
  - scope:
      path:         ""
      type:         skills
    values:
      layout:       skills
  # _info
  - scope:
      path:         ""
      type:         pages
    values:
      layout:       post
